version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - tf_version=$TERRAFORM_VERSION
      - wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - mv terraform /usr/local/bin/
  build:
    commands:
      - terraform --version
      - terraform init -input=false -backend=true -backend-config=params/$ENV/backend.tfvars -reconfigure
      - terraform plan --input=false -out tf.plan -var-file=params/$ENV/variables.tfvars -no-color
      - terraform apply "tf.plan"